from collections.abc import Callable
from typing import Any, Protocol

from password_manager.models.domain import Credential, VaultState


class VaultRepository(Protocol):
    def state(self) -> VaultState: ...

    def read_salt(self) -> bytes: ...

    def read_check(self) -> bytes: ...

    def read_tokens(self) -> list[bytes]: ...

    def initialize(self, salt: bytes, encrypted_check: bytes) -> None: ...

    def append_token(self, token: bytes) -> None: ...

    def reset(self) -> None: ...


class Cipher(Protocol):
    def encrypt(self, plaintext: bytes) -> bytes: ...

    def decrypt(self, token: bytes) -> bytes: ...


class CipherFactory(Protocol):
    def create(self, master_password: str, salt: bytes) -> Cipher: ...


class VaultServicePort(Protocol):
    def is_initialized(self) -> bool: ...

    def create(self, master_password: str) -> None: ...

    def unlock(self, master_password: str) -> None: ...

    def lock(self) -> None: ...

    def add_credential(self, credential: Credential) -> None: ...

    def list_credentials(self) -> list[Credential]: ...

    def reset(self) -> None: ...


class TaskRunner(Protocol):
    def submit(
        self,
        operation: Callable[[], Any],
        on_success: Callable[[Any], None],
        on_error: Callable[[Exception], None],
    ) -> bool: ...

    def close(self) -> None: ...


class Scheduler(Protocol):
    def call_later(self, milliseconds: int, callback: Callable[[], None]) -> Any: ...

    def cancel(self, handle: Any) -> None: ...


class ClipboardManager(Protocol):
    def copy(self, secret: str, lifetime_ms: int) -> None: ...

    def clear_if_owned(self) -> None: ...


class PyVaultView(Protocol):
    def show_unlock(self, creating: bool) -> None: ...

    def show_vault(self) -> None: ...

    def get_master_password(self) -> str: ...

    def get_master_password_confirmation(self) -> str: ...

    def get_credential_input(self) -> tuple[str, str, str]: ...

    def get_selected_index(self) -> int | None: ...

    def clear_unlock_fields(self) -> None: ...

    def clear_credential_fields(self) -> None: ...

    def set_busy(self, busy: bool) -> None: ...

    def set_status(self, message: str) -> None: ...

    def set_credentials(self, credentials: list[Credential]) -> None: ...

    def set_password_visible(self, index: int, password: str) -> None: ...

    def set_password_masked(self, index: int) -> None: ...

    def confirm_reset(self) -> bool: ...

    def show_info(self, title: str, message: str) -> None: ...

    def show_warning(self, title: str, message: str) -> None: ...

    def show_error(self, title: str, message: str) -> None: ...

    def close(self) -> None: ...
